name: franklin
services:
  gibneysolr:
    type: compose
    scanner: false # solr isn't running after lando start
    services:
      user: root
      image: quay.io/upennlibraries/upenn_solr:7.7.0
      ports:
        - '8983:8983'
      environment:
        LANDO_DROP_USER: solr
proxy:
  gibneysolr:
    - franklin.solr.lndo.site:8983
