#!/bin/bash
#
# runs Solr indexing using JRuby, in a docker container

CONTAINER_NAME="discovery-indexing-app"
IMAGE_NAME="discovery/discovery-indexing-app"
SCRIPT_PATH="$(readlink -f ${BASH_SOURCE[0]})"
# dir of this script, which should also be root of the repo
SCRIPT_DIR="$(dirname $SCRIPT_PATH)"

usage()
{
    echo "Usage: $0 MARC_FILE"
    echo "MARC_FILE needs to exist in the current directory"
    echo "tree, or container won't be able to access it."
    exit 1
}

[ $# -gt 0 ] || usage

# 'build' can be run each time we want to run the app; docker won't
# rebuild the image unless something has changed in the Dockerfile
echo "Building image"
docker build -f Dockerfile-jruby -t $IMAGE_NAME .

# remove old container image if there is one
docker ps -a | grep $CONTAINER_NAME > /dev/null
if [ $? == 0 ]; then
    echo "Removing existing image named $CONTAINER_NAME"
    docker rm $CONTAINER_NAME
fi

echo "Running indexing rake task"
docker run --name $CONTAINER_NAME -e MARC_FILE="$1" -v $SCRIPT_DIR:/opt/discovery $IMAGE_NAME
