version: 2.1

orbs:
  docker-publish: upenn-libraries/docker-publish@0.1.0

workflows:
  build_and_test:
    jobs:
      - docker-publish/publish:
          context: quay.io
          registry: quay.io
          image: upennlibraries/discovery-app
          label_prefix: edu.upenn.library
